runtime: python39  # or the Python version you are using
entrypoint: gunicorn -b :$PORT --log-level debug backend:app  # Replace 'main' with the name of your Python file containing the Flask app

handlers:
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /.*
  script: auto

# secrets.yaml is not included, you need to add it yourself, including:
# env_variables:
#  OPENAI_API_KEY: "your key here"

includes:
- secrets.yaml

env_variables:
  FLASK_DEBUG: 'True'
  # Environment variables (if any), like API keys
