runtime: python39  # or the Python version you are using
entrypoint: gunicorn -b :$PORT --log-level debug backend:app  # Replace 'main' with the name of your Python file containing the Flask app

#automatic_scaling:
 # min_idle_instances: 1  # Minimum number of idle instances
  #max_idle_instances: 2  # Maximum number of idle instances
  #min_pending_latency: 30ms  # Minimum amount of time that a request should wait in the pending queue
  #max_pending_latency: 50ms  # Maximum amount of time that a request should wait in the pending queue


handlers:
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /.*
  script: auto

includes:
- secrets.yaml

env_variables:
  FLASK_DEBUG: 'True'
  # Environment variables (if any), like API keys
